services:
  app:
    build: .
    container_name: django_app
    volumes:
      - ./data:/app/data
      - ./static:/app/staticfiles # статика
    environment:
      - DEBUG=0
      - DATABASE_URL=sqlite:///data/db.sqlite3
    expose:
      - "8000"
    restart: unless-stopped
    networks:
      - django

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/certs:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    depends_on:
      app:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - django

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    depends_on:
      nginx:
        condition: service_started
    command:
      - certonly
      - --webroot
      - -w
      - /var/www/certbot
      - --email
      - ${ADMIN_EMAIL}
      - --agree-tos
      - --no-eff-email
      - --non-interactive
      - -d
      - ${DOMAIN}
    networks:
      - django

volumes:
  certbot-www:

networks:
  django:
    driver: bridge